/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.featurevisor.sdk

//TODO: Add unit tests for Instance.kt later
//class InstanceTest {
//
//    private val systemUnderTest = FeaturevisorInstance.createInstance(
//        options = InstanceOptions(
//            bucketKeySeparator = "",
//            configureBucketKey = { feature: Feature, map: Map, s: String -> },
//            configureBucketValue = { feature: Feature, map: Map, i: Int -> },
//            datafile = null,
//            datafileUrl = null,
//            handleDatafileFetch = {},
//            initialFeatures = mapOf(),
//            interceptContext = {},
//            logger = null,
//            onActivation = {},
//            onReady = {},
//            onRefresh = {},
//            onUpdate = {},
//            refreshInterval = null,
//            stickyFeatures = mapOf()
//        )
//    )
//
//    @Test
//    fun `instance initialised properly`() {
//
//    }
//}
